# Documento 1: común
# primary
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

# secondary
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/

# tertiary
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/

---
# Documento 2: perfil 'pronoun'
spring:
  config:
    activate:
      on-profile: pronoun
words: "Yo,Tu,El,Ella"

---
# Documento 3: perfil 'verb'
spring:
  config:
    activate:
      on-profile: verb
words: "corrió, sabía, tenía, vio, compró"

---
# Documento 4: perfil 'article'
spring:
  config:
    activate:
      on-profile: article
words: "un,una,la"

---
# Documento 5: perfil 'adjective'
spring:
  config:
    activate:
      on-profile: adjective
words: "razonable, permeable, sospechoso, ordinario, improbable"

---
# Documento 6: perfil 'noun'
spring:
  config:
    activate:
      on-profile: noun
words: "barco, libro, voto, asiento, mochila, partición"
