# =========================
# Eureka CLIENT (común)
# =========================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

---
# =========================
# Perfil de entorno: local
# (para desarrollo en tu PC)
# =========================
spring:
  config:
    activate:
      on-profile: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/

---
# =========================
# Perfil de entorno: cluster
# (cuando usas el clúster de 3 Eureka)
# =========================
spring:
  config:
    activate:
      on-profile: cluster
eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
# Documento 2: perfil 'pronoun'
spring:
  config:
    activate:
      on-profile: pronoun
words: "Yo,Tu,El,Ella"

---
# Documento 3: perfil 'verb'
spring:
  config:
    activate:
      on-profile: verb
words: "corrió, sabía, tenía, vio, compró"

---
# Documento 4: perfil 'article'
spring:
  config:
    activate:
      on-profile: article
words: "un,una,la"

---
# Documento 5: perfil 'adjective'
spring:
  config:
    activate:
      on-profile: adjective
words: "razonable, permeable, sospechoso, ordinario, improbable"

---
# Documento 6: perfil 'noun'
spring:
  config:
    activate:
      on-profile: noun
words: "barco, libro, voto, asiento, mochila, partición"
